- view/manager-business-processes.js
reported here: https://github.com/egovernment/eregistrations-guatemala/issues/1016
> Translation issue - Notary account

- controller/manager-validation/index.js
- controller/manager-validation/server.js
- controller/users-admin/index.js
- controller/users-admin/server.js
- view/components/objects-table/manager.js
- view/components/users-table/manager.js
- view/users-table.js
Described in https://github.com/egovernment/eregistrations-guatemala/issues/1014.
> No redirect from table after user removal.

- status-logs/official-revision.js
Requested in https://github.com/egovernment/eregistrations-guatemala/issues/850.
> Sent back reasons in status log.

- apps-common/pdf-templates/business-process-status-log-print.html
- model/lib/status-log.js
- model/requirement-upload.js
- server/pdf-renderers/business-process-status-log-print.js
- server/services/certificates-status-log.js
- server/services/query-memory-db/queries/business-process-status-log.js
- server/services/status-log.js
- view/components/business-process-main-info.js
Requested in https://github.com/egovernment/eregistrations-guatemala/issues/810.
> Introduce officialFullName to status logs.

- model/document.js
- model/lib/status-log.js
- model/requirement-upload.js
I think we forgot about that, when we added status logs to certificates at #878 
Then they also should be read from snapshot when we visit certificate that has snapshot
> Include certificate status log in snapshot

- view/business-process-official-payment.js
- view/business-process-revision-payment.js
Just like for requirement upload custom sections, we need the possibility to append some sections to business-process-official-payment and business-process-revision-payment views.
> Allow inserting suctom sections in official payment views.

- view/business-process-revision.js
Reported here: https://github.com/egovernment/eregistrations-salvador/issues/1696
> Revision: Pause button is shown for the processed files

- server/services/query-memory-db/queries/notify-business-process-assigned.js
Hello team, 
I add an other particularity of `superuser` accounts here. If easy it would be great to set the notifications so that the superuser does not receive any emails. Let me know!
> Superuser and messages

- client/legacy/error-logger.js
> Filter IE extensions error

- css/components/dialog.css
- view/components/login-dialog.js
- view/components/register-dialog.js
- view/components/request-account-dialog.js
- view/components/reset-password-dialog.js
Login and register modals in demo mode miss close button, let's fix that.
Will fixe https://github.com/egovernment/eregistrations-salvador/issues/1718
> Add Close button for login/register modals in Demo

- css/components/document-preview.css
- view/business-process-revision-document.js
- view/business-process-revision-payment.js
`_if` passed directly to array which is handled dynamically, can break.
Following ensures no error occurs
Bug discovered through client error reporter
```
Client & Session Id:
------------------------------------
51481l5xduj4:019kok5rtgo7
User Agent:
------------------------------------
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
UTC Time:
------------------------------------
2017-02-17T20:34:35.914Z
Server Time:
------------------------------------
2017-02-17 21:34:35
Referer:
------------------------------------
https://miempresa.gob.sv/419iq65dthog/
User Id:
------------------------------------
17dobm9msjk
Application Name:
------------------------------------
official-revision
Application Access Id: …
```
> Fix reactivity issue in revision forms

- view/user-base.js
As requested here: https://github.com/egovernment/eregistrations-salvador/issues/1719
> Customisable demo banner

- view/business-process-guide.js
Needed for https://github.com/egovernment/eregistrations-salvador/issues/1720
> Allow customization of guide's registration headers

- test/utils/microsoft-excel-spreadsheet-mime-types.js
- utils/microsoft-excel-spreadsheet-mime-types.js
For https://github.com/egovernment/eregistrations-salvador/issues/1746 we need to add a mime type for allowed file types but also want to have it possible to easy use in other systems.
> Add Microsoft Excel mime type definitions for usage in end systems.

- view/business-process-base.js
Needed by https://github.com/egovernment/eregistrations-salvador/pull/1737
> Part A: Don't display documents page when no uploads are applicable.

- view/business-process-submission-forms.js
Followup to https://github.com/egovernment/eregistrations/pull/1688
> Allow customization of sworn declaration legend.

- webservice/export-catalogs.js
Open an endpoint with all enums used in the system
> Webservice - catalogs export

- client/legacy/refresh-guide.js
- view/business-process-guide.js
Case in which the document section is empty, a message: "You do not have to upload any documents for this service" should be displayed to inform that no documents must be uploaded.
> Part A3: Case in which no documents are asked to be uploaded

- routes/business-process-submitted.js
- routes/dispatcher.js
- routes/inspector.js
- routes/official-revision.js
- routes/official.js
- routes/supervisor.js
- routes/user.js
- routes/utils/inspector-match-first-certificate.js
- routes/utils/inspector-match-first-payment-receipt-upload.js
- routes/utils/inspector-match-first-requirement-upload.js
- routes/utils/official-match-first-certificate.js
- routes/utils/official-match-first-payment-receipt-upload.js
- routes/utils/official-match-first-requirement-upload.js
- routes/utils/user-match-first-certificate.js
- routes/utils/user-match-first-payment-receipt-upload.js
- routes/utils/user-match-first-requirement-upload.js
- view/business-process-official.js
- view/business-process-revision.js
- view/business-process-submitted.js
- view/components/business-process-documents-and-data-brief.js
This is in response to https://github.com/egovernment/eregistrations-salvador/pull/1737 that allow this situation.
> Part B: Allow business processes without uploads.

- view/utils/get-duration-days-hours-fine-grain.js
> Change formatting of times in new stats

- server/business-process-query/steps/reduce-time.js
- server/business-process-query/utils/reduce-time.js
We would like to use a truncated average instead of the average - we can truncate 10%
> Stats - times, smaller average

- model/dynamic-currency.js
- test/model/dynamic-currency.js
As mentioned here: 
https://github.com/egovernment/eregistrations-guatemala/issues/1081
> Allow decimals in dynamic currency definition

- scripts/generate-app/templates/client/css.index/official-revision.tpl
- scripts/generate-app/templates/client/css.index/official.tpl
See this: https://github.com/egovernment/eregistrations-guatemala/pull/1082
> Add missing statsistics table style to offcial apps generator templates

- view/statistics-time-per-person.js
- view/statistics-time-per-role.js
The 'days' display got back to the view...
> Regression in stats view

- bin/model-to-csv
- model/base.js
- model/business-process-new/base.js
- model/form-entities-table.js
- model/form-section-base.js
- model/form-section-group.js
- model/form-section-update.js
- model/form-section.js
- scripts/model-to-csv.js
This tool is to be used to generate csv formatted fields lists of services. It's main goal is to facilitate work on analysis by giving up to date overview of model.
> Tool for export of model fields in csv format

- view/user-base.js
https://unctad.atlassian.net/browse/EV2CORE-29
> Change the word "Tables" in the menu for "Files"

- css/base.css
- view/statistics-flow-operators.js
https://unctad.atlassian.net/browse/EV2CORE-9
> The pagination is overlapping the filters space

- view/statistics-time-per-person.js
https://unctad.atlassian.net/browse/EV2CORE-31
> Make consistent the space below a filter

- view/statistics-flow-certificates.js
- view/statistics-flow-rejections.js
- view/statistics-flow-roles.js
https://unctad.atlassian.net/browse/EV2CORE-38
> Too much space below the filters

- server/business-process-query/get-data.js
- server/business-process-query/steps/reduce-time.js
- server/routes/statistics.js
In both "Times / Per role" and in "Times / Roles - operator" tables, something would be very useful for us is to be able to see, for each "Processed file", what was the file, it operator, it time of processing, the start time and the end time based on which are calculated the time.
Proposals for display for Roles table : http://3m5fo4.axshare.com/#p=in_roles, for Roles/operators table: http://3m5fo4.axshare.com/#p=in_roles___operators (use as data specification)
> Prepare new data representation to be sent for Times / Per role and Times / Roles - operator tables

- view/statistics-flow-roles.js
https://unctad.atlassian.net/browse/EV2CORE-41
> Hide the "Pending" option in the selector, and have the "Validated" option selected by default.

- css/base.css
- view/statistics-flow-operators.js
https://unctad.atlassian.net/browse/EV2CORE-39
> Putting the Operators filter on the right of the Registrations filter

- view/components/table-columns.js
- view/utils/last-modified-date.js
- view/utils/last-modified.js
https://unctad.atlassian.net/browse/EV2CORE-5
> Remove the hours in the dates of the reasons of rejection.

- server/services/compute-processing-time.js
- utils/get-processing-working-hours-time.js
> processingWorkingHoursTime somehow got NaN value

- view/components/filter-bar/select-date-range.js
https://unctad.atlassian.net/browse/EV2CORE-52
> Date selector throwing errors

- bin/update-dependency
Filtered out files that should be synced:
* `scripts/generate-app/templates/.gitignore/` directory
* `server/env.js` file
> update-dependency script misses some files on eregistrations project

- css/base.css
- css/components/statistics-table.css
- view/statistics-time-per-person.js
- view/statistics-time-per-role.js
- view/utils/statistics-time-row-onclick.js
https://unctad.atlassian.net/browse/EV2CORE-45
> Implement the specific display for rejection reasons details

- view/statistics-flow-roles.js
https://unctad.atlassian.net/browse/EV2CORE-60
> Fix filter that goes to next line in Files/Roles

- apps-common/pdf-templates/statistics-flow-rejections.css
- apps-common/pdf-templates/statistics-flow-rejections.html
- server/csv-renderers/statistics-flow-rejections.js
- server/mongo-queries/get-rejection-reasons.js
- server/pdf-renderers/statistics-flow-rejections.js
- server/routes/statistics.js
- view/statistics-flow-rejections.js
It's about pdf and csv views of the new rejection reasons table.
> Rejection reasons - prepare pdf and csv

- view/components/filter-bar/select-date-range.js
https://unctad.atlassian.net/browse/EV2CORE-67
> Hide "Since start of the system" period in period selector

- server/routes/statistics.js
- utils/statistics-flow-rejection-reason-results.js
- view/statistics-flow-rejections.js
As described in the comment here: 
https://unctad.atlassian.net/browse/EV2CORE-3
1. we have lost the design of the table on your test port
2. the table is placed in a section that should be of class table-responsive-container (not doing this is going backwards for no reason) and not section-primary
3. we have lost the last column with the magnifying glass from which we could open the file
> Adjustments after tests

- css/base.css
https://unctad.atlassian.net/browse/EV2CORE-69
> Period selector : hide "clear" button

- test/utils/statistics-flow-rejection-reason-results.js
- utils/statistics-flow-rejection-reason-results.js
https://unctad.atlassian.net/browse/EV2CORE-82
> Use 1 as count for singular results in rejectionReasons occurreneces col

- scripts/migrate-status-history-to-mongo.js
- server/services/query-memory-db/queries/processing-step-status-history-entry.js
- server/services/status-history-logger.js
https://unctad.atlassian.net/browse/EV2CORE-78
> Migrate statusHsitory to mongo

- server/services/query-memory-db/queries/processing-step-status-history-entry.js
- server/services/status-history-logger.js
https://unctad.atlassian.net/browse/EV2CORE-79
decoument structure:
```javacript
{
service: {
id: '',
businessName: '',
}
processingStep: {
path: ''
label: ''
}
operator: {
id: '',
name: ''
},
status: {
code: '',
label: ''
},
date: {
date: 1494194400000,
ts: 1494232145990
}
}
```
> Adjust status log script to store statusHistory in mongo

- apps-common/pdf-templates/statistics-time-per-person.html
- apps-common/pdf-templates/statistics-time-per-role.html
- apps-common/query-conf/date-from.js
- server/csv-renderers/statistics-time-per-role.js
- server/mongo-queries/get-status-history.js
- server/pdf-renderers/statistics-time-per-person.js
- server/pdf-renderers/statistics-time-per-role.js
- server/routes/official.js
- server/routes/statistics.js
- server/routes/utils/accumulate-processing-time-items.js
- server/routes/utils/get-time-template.js
- server/routes/utils/resolve-time-per-person.js
- test/utils/processing-steps-meta-without-front-desk.js
- test/utils/to-date-time-in-time-zone.js
- utils/processing-steps-meta-without-front-desk.js
- utils/to-date-time-in-time-zone.js
- view/components/render-stats-overview.js
- view/statistics-time-per-person.js
- view/statistics-time-per-role.js
- view/utils/statistics-time-row-onclick.js
https://unctad.atlassian.net/browse/EV2CORE-80
> Enable querying for pending rows

- bin/update-dependency
@roxanadina Could you please test in on OSX?
> Use greadlink on OSX instead of readlink

- view/components/filter-bar/select-date-range.js
- view/utils/init-table-sorting-on-client.js
- view/utils/statistics-time-row-onclick.js
https://unctad.atlassian.net/browse/EV2CORE-121
> Server crash when in legacy in stats

- view/components/filter-bar/select-period-mode.js
https://unctad.atlassian.net/browse/EV2CORE-75
> Fix period group selector

- css/base.css
- css/components/statistics-table.css
- view/utils/statistics-time-row-onclick.js
https://unctad.atlassian.net/browse/EV2CORE-117
- have zero margin, so it does not look like a "table into a table"
- a grey background to make it pop out differently than the normal lines
> Make the details look different than the other rows

- css/components/statistics-table.css
- css/theme.default.min.css
- view/statistics-flow-certificates.js
- view/statistics-flow-operators.js
- view/statistics-flow-roles.js
This is the addition to https://unctad.atlassian.net/browse/EV2CORE-120 and https://github.com/egovernment/eregistrations/pull/1877
Contains a few fixes to make tables stay when you switch from year to week or day
> Force width on tables column fixes

- server/routes/statistics.js
https://unctad.atlassian.net/browse/EV2CORE-110
https://unctad.atlassian.net/browse/EV2CORE-111
> Add total line below thead - Files / Certificates

- server/routes/statistics.js
- view/statistics-dashboard.js
- view/statistics-files-completed.js
https://unctad.atlassian.net/browse/EV2CORE-122
> Put the table that is now in "Files" / Completed files in the Dashboard, with the Period selector

- view/components/filter-bar/select-date-range.js
As described here: https://unctad.atlassian.net/browse/EV2CORE-70
> Problem when loading business process from rejection reasons table

- server/business-process-query/get-status-history-date-map.js
- server/routes/statistics.js
- view/statistics-dashboard.js
https://unctad.atlassian.net/browse/EV2CORE-124
mockup: http://3m5fo4.axshare.com/#p=dashboard (second table)
> Duplicate the table in the Dashboard to show the details per certificate

- utils/statistics-flow-certificates-filter-result.js
https://unctad.atlassian.net/browse/EV2CORE-140
> Column artefact in stats certificates table

- model/form-entities-table.js
Inside that method iteration over formSections is not being done correctly.
It is done just over dataForms but instead it should be done over dataForms.map
> fix toMetaDataJSON method for form-entities-table

- server/routes/statistics.js
https://unctad.atlassian.net/browse/EV2CORE-131
> Remove the line "Total of corrections"

- server/routes/statistics.js
https://unctad.atlassian.net/browse/EV2CORE-132
> Times / having details for corrections

- model/processing-step.js
- server/services/query-memory-db/queries/business-process-rejection-reasons.js
https://unctad.atlassian.net/browse/EV2CORE-134
> Some rejections have no reason given

- view/statistics-files-roles.js
https://unctad.atlassian.net/browse/ELS-84
> Make the first column wider

- view/statistics-files-operators.js
- view/statistics-files-roles.js
- view/statistics-rejections.js
- view/utils/init-table-sorting-on-client.js
IT corresponds to following Jira tickets:
https://unctad.atlassian.net/browse/EV2CORE-107
https://unctad.atlassian.net/browse/EV2CORE-108
https://unctad.atlassian.net/browse/EV2CORE-109
> Enable sorting for roles, operators and rejections

- server/business-process-query/get-status-history-date-map.js
- server/routes/statistics.js
https://unctad.atlassian.net/browse/EV2CORE-141
> Dashboard table 1 : all the files that are either in status Withdraw_0 or Withdraw_1

- server/services/query-memory-db/queries/business-process-ws-json.js
- server/services/status-history-logger.js
- webservice/request-logger.js
This set of tools enables easier handling of WS communication.
> WS communication utilities

- apps-common/pdf-templates/statistics-issued-certificates.css
- apps-common/pdf-templates/statistics-issued-certificates.html
- model/business-process-new/certificates.js
- model/document.js
- model/lib/certificate-category.js
- routes/statistics.js
- server/csv-renderers/statistics-issued-certificates.js
- server/pdf-renderers/statistics-issued-certificates.js
- server/routes/statistics.js
- test/model/lib/certificate-category.js
- view/statistics-certificates-issued.js
- view/statistics-files.js
- view/user-base.js
- view/utils/statistics-certificates-issued-query-server.js
https://unctad.atlassian.net/browse/EV2CORE-151
mockup: http://3m5fo4.axshare.com/#p=certificates_issued
> Change data for Files / Certificates

- server/services/ws-services-requests-manager.js
- webservice/request-logger.js
https://unctad.atlassian.net/browse/EV2CORE-153
> Service enabling resending of requests

- model/base.js
- model/business-process-new/base.js
- model/cost.js
- model/document.js
- model/form-entities-table.js
- model/form-section-group.js
- model/form-section-update.js
- model/form-section.js
- model/processing-step.js
- model/requirement-upload.js
https://unctad.atlassian.net/browse/EV2CORE-169
> Expose keyPath on fields

- server/services/ws-services-requests-manager.js
- webservice/request-logger.js
https://unctad.atlassian.net/browse/EV2CORE-175
> Fix resender logic

- model/processing-step.js
https://unctad.atlassian.net/browse/ELS-113
> Add revision operator email in sent data

- server/utils/get-file-from-url.js
- webservice/utils/download-certificates-files.js
Needed for: https://github.com/egovernment/eregistrations-salvador/pull/1893/files
as required in https://unctad.atlassian.net/browse/ELS-89
> #1909 initial version of util

- server/services/query-memory-db/queries/add-user.js
- webservice/utils/add-user-by-email.js
https://unctad.atlassian.net/browse/ELS-118
> Receive local operator email along with answer from CNR

- model/cost.js
- model/lib/currency.js
- test/model/lib/currency.js
https://unctad.atlassian.net/browse/ELS-121
> Add normalize more suiting for Currencies

- .lint
- routes/statistics.js
- server/routes/statistics.js
- view/statistics-dashboard-old.js
- view/statistics-dashboard.js
- view/user-base.js
https://unctad.atlassian.net/browse/EV2CORE-164
> Rearrange the dashboard

- .lint
- routes/statistics.js
- scripts/migrate-status-history-to-mongo.js
- server/mongo-queries/get-status-history.js
- server/routes/statistics.js
- view/statistics-dashboard-old.js
- view/statistics-dashboard.js
- view/user-base.js
https://unctad.atlassian.net/browse/EV2CORE-165
> Sent back for correction table

- server/routes/statistics.js
- view/statistics-dashboard.js
https://unctad.atlassian.net/browse/EV2CORE-167
> Processing times per role overview

- model/form-entities-table.js
https://unctad.atlassian.net/browse/EV2CORE-49
> toWebServiceJSON crash

- view/dbjs/pickup-institution-form-section.js
Needed for: https://github.com/egovernment/eregistrations-salvador/issues/1962
> Enable more fields in pickupInstitution section

- webservice/utils/add-user-by-email.js
Needed for: https://github.com/egovernment/eregistrations-salvador/pull/1929
> Enable adding roles when adding user from ws

- server/services/status-history-logger.js
https://unctad.atlassian.net/browse/EV2CORE-193
> Some temp fix

- server/services/ws-services-requests-manager.js
Needed for: https://github.com/egovernment/eregistrations-salvador/issues/2027
> Add flag to explicity exclude ws from resend

- utils/get-soap-client.js
Solves: https://unctad.atlassian.net/browse/ELS-242
> Shorten timeouts for ws on attempt to get wsdl

- controller/demo-user/client.js
- controller/demo-user/server.js
- controller/public/client.js
- controller/users-admin/server.js
- server/email-notifications/create-account.js
https://unctad.atlassian.net/browse/EV2CORE-192
> User validation - allow a flag in environment file that sets this

- test/utils/copy-by-paths.js
- utils/copy-by-paths.js
Needed by: https://github.com/egovernment/eregistrations-salvador/issues/2068 (https://unctad.atlassian.net/browse/ELS-279)
> Enable error suppression in error copying util

- server/middlewares/allowed-http-methods.js
This is part of solution to https://unctad.atlassian.net/browse/ELS-233
> Middleware to handle improper http methods

- view/inspector.js
As requested here https://unctad.atlassian.net/browse/ELS-277 , https://github.com/egovernment/eregistrations-salvador/pull/2076
> Enable custom addition in inspector view filters

- controller/common/profile/client.js
- controller/common/profile/index.js
- controller/common/profile/server-old-hash.js
- controller/common/profile/server.js
- controller/common/request-create-account/index.js
- controller/user/client.js
- controller/user/index.js
- controller/user/server-old-hash.js
- controller/user/server.js
- server/oauth.js
- view/manager.js
- view/user-base.js
https://unctad.atlassian.net/browse/ELS-308
> Allow manager to change his v2 profile

- client/legacy/build-costs-print-link.js
- client/legacy/refresh-guide.js
Needed for https://unctad.atlassian.net/browse/ELS-280
> Move buildCostsPrintLink to it's own legacy utility.

- css/components/fa.css
Needed for: https://unctad.atlassian.net/browse/TOBE-1699
> Add new fa icons styles

- model/base.js
- model/cost.js
For currency type entries we want: value and currency keys.
> Split currency in toWSJSON

- test/utils/json-to-observables.js
- utils/json-to-observables.js
- view/components/table-columns.js
- view/user-home.js
- view/user-requests.js
Needed for: https://unctad.atlassian.net/browse/ELS-283
> Helpers for json to observables
